In [440]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Data Wrangling

In [441]:
df = pd.read_csv("./dataset/SOF PUF 2023 - Clean.csv")
df.drop(columns=["Unnamed: 0", "Remittance Spent", "Past 6 Months Indicator"], inplace=True)
df = df.rename(columns={"Cash Home" : "Cash Brought Home"})
df.head()

,Region,Relationship,Sex,Age,Times Left the Country,Month of Last Departure,Year of Last Departure,Marital Status,Education Level,Usual Work,...,Other,Consumptions Percent,Investments Percent,Savings Percent,Gift/Donation Percent,Other Percent,Returned Apr-Sep,Cash Brought Home,Receive Goods/Products,Total Imputed Value of Goods/Products
0,Ilocos,Other,Male,65,1,March,2023,Married/Living Together,Junior High Graduate,"Skilled Agricultural, Forestry and Fishery Wor...",...,False,100.0,0.0,0.0,0.0,0.0,No,NaN,Yes,55000.0
1,Ilocos,Other,Female,72,1,March,2023,Married/Living Together,Junior High Graduate,Elementary Occupations,...,False,NaN,NaN,NaN,NaN,NaN,No,NaN,No,NaN
2,Ilocos,Other,Female,30,1,March,2023,Single,College Graduate,Professionals,...,False,NaN,NaN,NaN,NaN,NaN,No,NaN,No,NaN
3,Ilocos,Child,Female,42,2,September,2023,Widowed,Junior High Graduate,Elementary Occupations,...,False,100.0,0.0,0.0,0.0,0.0,Yes,20000.0,Yes,30000.0
4,Ilocos,Spouse,Female,43,1,April,2023,Married/Living Together,College Graduate,Elementary Occupations,...,False,100.0,0.0,0.0,0.0,0.0,No,NaN,No,NaN

In [442]:
print("columns:", *df.columns, sep="\n")

columns:
Region
Relationship
Sex
Age
Times Left the Country
Month of Last Departure
Year of Last Departure
Marital Status
Education Level
Usual Work
Reason for Leaving
Base
Country Stayed
Expected Return (Months)
Worked Abroad
Work
Industry
Average Monthly Income
Months Worked
Returned
Month Returned
Year Returned
Return Reason
Expected Month Returned
Expected Year Returned
Remittance Received
Cash Remittance
Mode of Remittance
Consumptions
Investments
Savings
Gift/Donation
Other
Consumptions Percent
Investments Percent
Savings Percent
Gift/Donation Percent
Other Percent
Returned Apr-Sep
Cash Brought Home
Receive Goods/Products
Total Imputed Value of Goods/Products

In [443]:
df['Marital Status'] = df['Marital Status'].replace('Unknown', np.nan)

In [444]:
# Checking for missing values
df.isnull().sum()

Region                                      0
Relationship                                0
Sex                                         0
Age                                         0
Times Left the Country                      0
Month of Last Departure                     0
Year of Last Departure                      0
Marital Status                              9
Education Level                           159
Usual Work                                  4
Reason for Leaving                          0
Base                                      729
Country Stayed                              0
Expected Return (Months)                    0
Worked Abroad                               0
Work                                      692
Industry                                  692
Average Monthly Income                    692
Months Worked                             692
Returned                                    0
Month Returned                           2771
Year Returned                            2771
Return Reason                            2771
Expected Month Returned                  1911
Expected Year Returned                   1912
Remittance Received                         0
Cash Remittance                          1424
Mode of Remittance                       1441
Consumptions                                0
Investments                                 0
Savings                                     0
Gift/Donation                               0
Other                                       0
Consumptions Percent                     1441
Investments Percent                      1451
Savings Percent                          1441
Gift/Donation Percent                    1450
Other Percent                            1455
Returned Apr-Sep                            0
Cash Brought Home                        3510
Receive Goods/Products                      0
Total Imputed Value of Goods/Products    3898
dtype: int64

In [445]:
print(df["Education Level"].isnull().sum()/df.shape[0]*100)
# Education level is only missing 3.69% of its data, therefore the column still holds some signifance.

3.6942379182156135

In [446]:
# Imputing the missing values with the most frequent answer
df["Education Level"] = df["Education Level"].fillna(df["Education Level"].mode()[0])
df["Education Level"].unique()

<StringArray>
[                                     'Junior High Graduate',
                                          'College Graduate',
                                 'Junior High Undergraduate',
 'Post-Secondary Non-Tertiary/Technical-Vocational Graduate',
                                     'College Undergraduate',
                                  'Elementary Undergraduate',
                                       'Elementary Graduate',
                         'Post Baccalaureate/ Post Graduate',
                                 'Senior High Undergraduate',
                                      'Senior High Graduate',
                              'Post Secondary Undergraduate']
Length: 11, dtype: str

In [447]:
df["Usual Work"] = df["Usual Work"].replace(np.nan, "Unemployed")
df["Usual Work"].unique()

<StringArray>
['Skilled Agricultural, Forestry and Fishery Workers',
                             'Elementary Occupations',
                                      'Professionals',
                          'Service and Sales Workers',
                            'Non-gainful occupations',
         'Plant and Machine Operators and Assemblers',
                           'Clerical Support Workers',
                                           'Managers',
            'Technicians and Associate Professionals',
                   'Craft and Related Trades Workers',
                                         'Unemployed',
                           'Armed Forces Occupations']
Length: 12, dtype: str

In [448]:
print(df["Base"].isnull().sum()/df.shape[0]*100)
# The base is missing 16.93% of its data, still safe to be used.
df[df["Base"].isnull()]
# Base is NA due to tourist (Overseas Filipino Workers who simply traveled to be a tourist

16.937732342007436

,Region,Relationship,Sex,Age,Times Left the Country,Month of Last Departure,Year of Last Departure,Marital Status,Education Level,Usual Work,...,Other,Consumptions Percent,Investments Percent,Savings Percent,Gift/Donation Percent,Other Percent,Returned Apr-Sep,Cash Brought Home,Receive Goods/Products,Total Imputed Value of Goods/Products
0,Ilocos,Other,Male,65,1,March,2023,Married/Living Together,Junior High Graduate,"Skilled Agricultural, Forestry and Fishery Wor...",...,False,100.0,0.0,0.0,0.0,0.0,No,NaN,Yes,55000.0
1,Ilocos,Other,Female,72,1,March,2023,Married/Living Together,Junior High Graduate,Elementary Occupations,...,False,NaN,NaN,NaN,NaN,NaN,No,NaN,No,NaN
2,Ilocos,Other,Female,30,1,March,2023,Single,College Graduate,Professionals,...,False,NaN,NaN,NaN,NaN,NaN,No,NaN,No,NaN
5,Ilocos,Other,Female,73,1,January,2023,Widowed,Junior High Graduate,Elementary Occupations,...,False,NaN,NaN,NaN,NaN,NaN,No,NaN,No,NaN
12,Ilocos,Child,Female,28,1,July,2023,Married/Living Together,Junior High Graduate,Service and Sales Workers,...,False,NaN,NaN,NaN,NaN,NaN,No,NaN,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4158,ARMM,Spouse,Male,56,1,May,2023,Married/Living Together,Elementary Undergraduate,"Skilled Agricultural, Forestry and Fishery Wor...",...,False,NaN,NaN,NaN,NaN,NaN,No,NaN,No,NaN
4178,ARMM,Child,Female,45,1,July,2023,Married/Living Together,Elementary Graduate,Elementary Occupations,...,False,NaN,NaN,NaN,NaN,NaN,Yes,5000.0,No,NaN
4183,ARMM,Head,Male,52,1,February,2020,Married/Living Together,Junior High Graduate,"Skilled Agricultural, Forestry and Fishery Wor...",...,False,NaN,NaN,NaN,NaN,NaN,No,NaN,Yes,35000.0
4211,ARMM,Head,Male,24,1,November,2019,Married/Living Together,Senior High Graduate,Plant and Machine Operators and Assemblers,...,False,NaN,NaN,NaN,NaN,NaN,No,NaN,No,NaN
4281,ARMM,Spouse,Female,36,1,September,2023,Married/Living Together,Elementary Undergraduate,Elementary Occupations,...,False,NaN,NaN,NaN,NaN,NaN,No,NaN,No,NaN

In [449]:
# changing base to N/A for tourist
df[df["Reason for Leaving"] == "Tourist"][["Reason for Leaving", "Base", "Worked Abroad", "Work"]]
# Since there are some tourist that found work abroad we cannot generalize the missing values are Not Applicable for base/work.

     Reason for Leaving Base Worked Abroad Work
34              Tourist  NaN            No  NaN
35              Tourist  NaN            No  NaN
36              Tourist  NaN            No  NaN
37              Tourist  NaN            No  NaN
48              Tourist  NaN            No  NaN
...                 ...  ...           ...  ...
4131            Tourist  NaN            No  NaN
4158            Tourist  NaN            No  NaN
4178            Tourist  NaN            No  NaN
4183            Tourist  NaN            No  NaN
4211            Tourist  NaN            No  NaN

[601 rows x 4 columns]

In [450]:
is_tourist=df["Reason for Leaving"] == "Tourist"
tourist_who_worked= is_tourist & df["Industry"].notna()
true_tourist=is_tourist & df["Industry"].isna()

In [451]:
df[tourist_who_worked][["Reason for Leaving", "Base", "Worked Abroad", "Work", "Industry", "Average Monthly Income", "Months Worked"]]

,Reason for Leaving,Base,Worked Abroad,Work,Industry,Average Monthly Income,Months Worked
2307,Tourist,NaN,Yes,Professionals,"Arts, Entertainment and Recreation",15000.0,0.0
3960,Tourist,NaN,Yes,Service and Sales Workers,Wholesale and Retail Trade; Repair of Motor Ve...,25000.0,9.0

In [452]:
df[true_tourist][["Reason for Leaving", "Base", "Work", 'Worked Abroad', "Industry", "Average Monthly Income", "Months Worked"]]

,Reason for Leaving,Base,Work,Worked Abroad,Industry,Average Monthly Income,Months Worked
34,Tourist,NaN,NaN,No,NaN,NaN,NaN
35,Tourist,NaN,NaN,No,NaN,NaN,NaN
36,Tourist,NaN,NaN,No,NaN,NaN,NaN
37,Tourist,NaN,NaN,No,NaN,NaN,NaN
48,Tourist,NaN,NaN,No,NaN,NaN,NaN
...,...,...,...,...,...,...,...
4131,Tourist,NaN,NaN,No,NaN,NaN,NaN
4158,Tourist,NaN,NaN,No,NaN,NaN,NaN
4178,Tourist,NaN,NaN,No,NaN,NaN,NaN
4183,Tourist,NaN,NaN,No,NaN,NaN,NaN
4211,Tourist,NaN,NaN,No,NaN,NaN,NaN

In [453]:
df.loc[tourist_who_worked, "Worked Abroad"] = "Yes"
df.loc[tourist_who_worked & df.Base.isna(), "Base" ] = "Land-based"
df[tourist_who_worked][["Reason for Leaving", "Base", "Worked Abroad", "Work", "Industry", "Average Monthly Income", "Months Worked"]]

,Reason for Leaving,Base,Worked Abroad,Work,Industry,Average Monthly Income,Months Worked
2307,Tourist,Land-based,Yes,Professionals,"Arts, Entertainment and Recreation",15000.0,0.0
3960,Tourist,Land-based,Yes,Service and Sales Workers,Wholesale and Retail Trade; Repair of Motor Ve...,25000.0,9.0

In [454]:
df.loc[true_tourist, "Worked Abroad"] = "No"
df.loc[true_tourist, ["Base", "Industry", "Work"]] = "N/A"
df.loc[true_tourist, ["Average Monthly Income", "Months Worked"]] = 0.0
df[true_tourist][["Reason for Leaving", "Base", "Work", "Worked Abroad", "Industry", "Average Monthly Income", "Months Worked"]]

,Reason for Leaving,Base,Work,Worked Abroad,Industry,Average Monthly Income,Months Worked
34,Tourist,N/A,N/A,No,N/A,0.0,0.0
35,Tourist,N/A,N/A,No,N/A,0.0,0.0
36,Tourist,N/A,N/A,No,N/A,0.0,0.0
37,Tourist,N/A,N/A,No,N/A,0.0,0.0
48,Tourist,N/A,N/A,No,N/A,0.0,0.0
...,...,...,...,...,...,...,...
4131,Tourist,N/A,N/A,No,N/A,0.0,0.0
4158,Tourist,N/A,N/A,No,N/A,0.0,0.0
4178,Tourist,N/A,N/A,No,N/A,0.0,0.0
4183,Tourist,N/A,N/A,No,N/A,0.0,0.0
4211,Tourist,N/A,N/A,No,N/A,0.0,0.0

In [455]:
df[~is_tourist & df["Base"].isna() & (df["Worked Abroad"] == "No")][["Reason for Leaving", "Base", "Work", "Worked Abroad", "Industry", "Average Monthly Income", "Months Worked"]]

,Reason for Leaving,Base,Work,Worked Abroad,Industry,Average Monthly Income,Months Worked
1,Immigrant,NaN,NaN,No,NaN,NaN,NaN
5,Immigrant,NaN,NaN,No,NaN,NaN,NaN
12,Immigrant,NaN,NaN,No,NaN,NaN,NaN
13,Immigrant,NaN,NaN,No,NaN,NaN,NaN
29,Immigrant,NaN,NaN,No,NaN,NaN,NaN
...,...,...,...,...,...,...,...
4070,"Others, specify",NaN,NaN,No,NaN,NaN,NaN
4075,"Others, specify",NaN,NaN,No,NaN,NaN,NaN
4084,Student,NaN,NaN,No,NaN,NaN,NaN
4117,Student,NaN,NaN,No,NaN,NaN,NaN
4281,"Others, specify",NaN,NaN,No,NaN,NaN,NaN

In [456]:
df.loc[~is_tourist & df["Base"].isna() & (df["Worked Abroad"] == "No"), ['Average Monthly Income', 'Months Worked']] = 0
df.loc[~is_tourist & df["Base"].isna() & (df["Worked Abroad"] == "No"), ['Work', 'Base', "Industry"]] = "N/A"
df[~is_tourist & (df["Base"] == "N/A") &  (df["Worked Abroad"] == "No")][["Reason for Leaving", "Base", "Work", "Worked Abroad", "Industry", "Average Monthly Income", "Months Worked"]]

,Reason for Leaving,Base,Work,Worked Abroad,Industry,Average Monthly Income,Months Worked
1,Immigrant,N/A,N/A,No,N/A,0.0,0.0
5,Immigrant,N/A,N/A,No,N/A,0.0,0.0
12,Immigrant,N/A,N/A,No,N/A,0.0,0.0
13,Immigrant,N/A,N/A,No,N/A,0.0,0.0
29,Immigrant,N/A,N/A,No,N/A,0.0,0.0
...,...,...,...,...,...,...,...
4070,"Others, specify",N/A,N/A,No,N/A,0.0,0.0
4075,"Others, specify",N/A,N/A,No,N/A,0.0,0.0
4084,Student,N/A,N/A,No,N/A,0.0,0.0
4117,Student,N/A,N/A,No,N/A,0.0,0.0
4281,"Others, specify",N/A,N/A,No,N/A,0.0,0.0

In [457]:
df[df["Base"].isna()][["Reason for Leaving", "Base", "Work", "Worked Abroad", "Industry", "Average Monthly Income", "Months Worked"]]

,Reason for Leaving,Base,Work,Worked Abroad,Industry,Average Monthly Income,Months Worked
0,Immigrant,NaN,Elementary Occupations,Yes,Construction,168960.0,6.0
2,Immigrant,NaN,Professionals,Yes,Human Health and Social Work Activities,50000.0,6.0
19,Immigrant,NaN,Service and Sales Workers,Yes,Wholesale and Retail Trade; Repair of Motor Ve...,153600.0,6.0
20,Immigrant,NaN,Service and Sales Workers,Yes,Wholesale and Retail Trade; Repair of Motor Ve...,153600.0,6.0
23,Immigrant,NaN,Service and Sales Workers,Yes,Accommodation and Food Service Activities,150000.0,60.0
38,Immigrant,NaN,Clerical Support Workers,Yes,Administrative and Support Service Activities,120000.0,8.0
39,Immigrant,NaN,Service and Sales Workers,Yes,Accommodation and Food Service Activities,100000.0,48.0
44,Immigrant,NaN,Clerical Support Workers,Yes,"Professional, Scientific and Technical Activities",60000.0,45.0
45,Immigrant,NaN,Clerical Support Workers,Yes,Administrative and Support Service Activities,40000.0,45.0
46,Immigrant,NaN,Clerical Support Workers,Yes,Administrative and Support Service Activities,40000.0,45.0
52,Immigrant,NaN,Service and Sales Workers,Yes,Administrative and Support Service Activities,40000.0,33.0
53,Immigrant,NaN,Clerical Support Workers,Yes,Administrative and Support Service Activities,60000.0,33.0
54,Immigrant,NaN,Service and Sales Workers,Yes,Other Service Activities,224000.0,58.0
59,Immigrant,NaN,Professionals,Yes,Education,120000.0,51.0
60,Immigrant,NaN,Professionals,Yes,Human Health and Social Work Activities,200000.0,51.0
64,Immigrant,NaN,Professionals,Yes,Human Health and Social Work Activities,120000.0,49.0
88,Immigrant,NaN,Elementary Occupations,Yes,Other Service Activities,30000.0,41.0
89,Immigrant,NaN,Craft and Related Trades Workers,Yes,Manufacturing,30000.0,32.0
108,Immigrant,NaN,Elementary Occupations,Yes,Manufacturing,60000.0,52.0
867,Work with Philippine Embassy/Consulate Abroad,NaN,Plant and Machine Operators and Assemblers,Yes,Transportation and Storage,30000.0,8.0
1399,Immigrant,NaN,Professionals,Yes,Administrative and Support Service Activities,50000.0,59.0
2016,Immigrant,NaN,Elementary Occupations,Yes,Manufacturing,30000.0,36.0
2152,Immigrant,NaN,Clerical Support Workers,Yes,Manufacturing,200000.0,5.0
2165,Immigrant,NaN,Professionals,Yes,Human Health and Social Work Activities,500000.0,40.0
2238,Student,NaN,Clerical Support Workers,Yes,Education,15000.0,8.0
2260,Immigrant,NaN,Clerical Support Workers,Yes,Accommodation and Food Service Activities,35000.0,46.0
2269,Immigrant,NaN,Plant and Machine Operators and Assemblers,Yes,Administrative and Support Service Activities,20000.0,9.0
2280,Student,NaN,Service and Sales Workers,Yes,Human Health and Social Work Activities,300000.0,10.0
2424,Work with Philippine Embassy/Consulate Abroad,NaN,Technicians and Associate Professionals,Yes,Wholesale and Retail Trade; Repair of Motor Ve...,120000.0,60.0
2634,"Others, specify",NaN,Elementary Occupations,Yes,Accommodation and Food Service Activities,50000.0,18.0
2672,"Others, specify",NaN,Professionals,Yes,Human Health and Social Work Activities,60000.0,35.0
3214,Immigrant,NaN,Technicians and Associate Professionals,Yes,Information and Communication,30000.0,21.0
3242,Immigrant,NaN,Technicians and Associate Professionals,Yes,Human Health and Social Work Activities,200000.0,34.0
3792,Work with Philippine Embassy/Consulate Abroad,NaN,Elementary Occupations,Yes,Other Service Activities,20000.0,7.0
3801,Student,NaN,Elementary Occupations,Yes,Other Service Activities,20000.0,10.0
3802,Work with Philippine Embassy/Consulate Abroad,NaN,Plant and Machine Operators and Assemblers,Yes,Public Administration and Defense; Compulsory ...,40000.0,50.0
4001,Immigrant,NaN,Service and Sales Workers,Yes,Wholesale and Retail Trade; Repair of Motor Ve...,15000.0,36.0

In [458]:
df.loc[df["Base"].isna(), "Base"] = df["Base"].mode()[0]
df.Base

0       Land-based
1              N/A
2       Land-based
3       Land-based
4       Land-based
           ...
4299    Land-based
4300    Land-based
4301    Land-based
4302    Land-based
4303    Land-based
Name: Base, Length: 4304, dtype: str

In [459]:
df[df["Work"].isna()][["Reason for Leaving", "Base", "Worked Abroad", "Work", "Industry", "Average Monthly Income", "Months Worked"]]

,Reason for Leaving,Base,Worked Abroad,Work,Industry,Average Monthly Income,Months Worked
766,Overseas Filipino Worker (OFW) with Contract,Land-based,No,NaN,NaN,NaN,NaN
2511,Other OFW with no Contract,Land-based,No,NaN,NaN,NaN,NaN

In [460]:
contradictory_rows = df['Reason for Leaving'].str.contains('OFW', na=False) & (df['Worked Abroad'] == 'No')
df = df[~contradictory_rows]
df[df["Work"].isna()][["Reason for Leaving", "Base", "Worked Abroad", "Work", "Industry", "Average Monthly Income", "Months Worked"]]

Empty DataFrame
Columns: [Reason for Leaving, Base, Worked Abroad, Work, Industry, Average Monthly Income, Months Worked]
Index: []

In [461]:
df.isnull().sum()

Region                                      0
Relationship                                0
Sex                                         0
Age                                         0
Times Left the Country                      0
Month of Last Departure                     0
Year of Last Departure                      0
Marital Status                              9
Education Level                             0
Usual Work                                  0
Reason for Leaving                          0
Base                                        0
Country Stayed                              0
Expected Return (Months)                    0
Worked Abroad                               0
Work                                        0
Industry                                    0
Average Monthly Income                      0
Months Worked                               0
Returned                                    0
Month Returned                           2769
Year Returned                            2769
Return Reason                            2769
Expected Month Returned                  1911
Expected Year Returned                   1912
Remittance Received                         0
Cash Remittance                          1423
Mode of Remittance                       1440
Consumptions                                0
Investments                                 0
Savings                                     0
Gift/Donation                               0
Other                                       0
Consumptions Percent                     1440
Investments Percent                      1450
Savings Percent                          1440
Gift/Donation Percent                    1449
Other Percent                            1454
Returned Apr-Sep                            0
Cash Brought Home                        3508
Receive Goods/Products                      0
Total Imputed Value of Goods/Products    3898
dtype: int64

In [462]:
df[['Returned', "Month Returned", "Year Returned", "Return Reason", "Expected Month Returned", "Expected Year Returned"]]

,Returned,Month Returned,Year Returned,Return Reason,Expected Month Returned,Expected Year Returned
0,No,NaN,NaN,NaN,NaN,NaN
1,No,NaN,NaN,NaN,NaN,NaN
2,No,NaN,NaN,NaN,NaN,NaN
3,No,NaN,NaN,NaN,September,2027.0
4,No,NaN,NaN,NaN,April,2025.0
...,...,...,...,...,...,...
4299,No,NaN,NaN,NaN,June,2024.0
4300,No,NaN,NaN,NaN,October,2027.0
4301,No,NaN,NaN,NaN,May,2024.0
4302,No,NaN,NaN,NaN,March,2024.0
4303,No,NaN,NaN,NaN,NaN,NaN

In [463]:
df[df['Returned']=="No"][['Returned', "Month Returned", "Year Returned", "Return Reason", "Expected Month Returned", "Expected Year Returned"]]

,Returned,Month Returned,Year Returned,Return Reason,Expected Month Returned,Expected Year Returned
0,No,NaN,NaN,NaN,NaN,NaN
1,No,NaN,NaN,NaN,NaN,NaN
2,No,NaN,NaN,NaN,NaN,NaN
3,No,NaN,NaN,NaN,September,2027.0
4,No,NaN,NaN,NaN,April,2025.0
...,...,...,...,...,...,...
4299,No,NaN,NaN,NaN,June,2024.0
4300,No,NaN,NaN,NaN,October,2027.0
4301,No,NaN,NaN,NaN,May,2024.0
4302,No,NaN,NaN,NaN,March,2024.0
4303,No,NaN,NaN,NaN,NaN,NaN

In [464]:
not_returned = (df['Returned'] == "No") & (df["Month Returned"].isna()) & (df["Year Returned"].isna()) & (df['Return Reason'].isna())

df["Month Returned"].info()
df["Year Returned"].info()
df["Return Reason"].info()

df.loc[not_returned, ["Month Returned", "Return Reason"]] = np.nan
df.loc[not_returned, "Year Returned"] = np.nan

df[df['Returned']=="No"][['Returned', "Month Returned", "Year Returned", "Return Reason", "Expected Month Returned", "Expected Year Returned"]]

<class 'pandas.Series'>
Index: 4302 entries, 0 to 4303
Series name: Month Returned
Non-Null Count  Dtype
--------------  -----
1533 non-null   str
dtypes: str(1)
memory usage: 67.2 KB
<class 'pandas.Series'>
Index: 4302 entries, 0 to 4303
Series name: Year Returned
Non-Null Count  Dtype
--------------  -----
1533 non-null   float64
dtypes: float64(1)
memory usage: 67.2 KB
<class 'pandas.Series'>
Index: 4302 entries, 0 to 4303
Series name: Return Reason
Non-Null Count  Dtype
--------------  -----
1533 non-null   str
dtypes: str(1)
memory usage: 67.2 KB

,Returned,Month Returned,Year Returned,Return Reason,Expected Month Returned,Expected Year Returned
0,No,NaN,NaN,NaN,NaN,NaN
1,No,NaN,NaN,NaN,NaN,NaN
2,No,NaN,NaN,NaN,NaN,NaN
3,No,NaN,NaN,NaN,September,2027.0
4,No,NaN,NaN,NaN,April,2025.0
...,...,...,...,...,...,...
4299,No,NaN,NaN,NaN,June,2024.0
4300,No,NaN,NaN,NaN,October,2027.0
4301,No,NaN,NaN,NaN,May,2024.0
4302,No,NaN,NaN,NaN,March,2024.0
4303,No,NaN,NaN,NaN,NaN,NaN

In [465]:
df[(df['Returned']=="No") & (df["Reason for Leaving"] == "Immigrant")][["Reason for Leaving", "Expected Month Returned", "Expected Year Returned", "Return Reason"]]

,Reason for Leaving,Expected Month Returned,Expected Year Returned,Return Reason
0,Immigrant,NaN,NaN,NaN
1,Immigrant,NaN,NaN,NaN
2,Immigrant,NaN,NaN,NaN
5,Immigrant,NaN,NaN,NaN
12,Immigrant,NaN,NaN,NaN
13,Immigrant,NaN,NaN,NaN
19,Immigrant,NaN,NaN,NaN
20,Immigrant,NaN,NaN,NaN
23,Immigrant,June,2024.0,NaN
29,Immigrant,NaN,NaN,NaN
38,Immigrant,NaN,NaN,NaN
39,Immigrant,December,2023.0,NaN
44,Immigrant,NaN,NaN,NaN
45,Immigrant,NaN,NaN,NaN
46,Immigrant,NaN,NaN,NaN
47,Immigrant,NaN,NaN,NaN
52,Immigrant,NaN,NaN,NaN
53,Immigrant,NaN,NaN,NaN
54,Immigrant,NaN,NaN,NaN
56,Immigrant,NaN,NaN,NaN
59,Immigrant,NaN,NaN,NaN
60,Immigrant,NaN,NaN,NaN
64,Immigrant,NaN,NaN,NaN
85,Immigrant,NaN,NaN,NaN
86,Immigrant,NaN,NaN,NaN
88,Immigrant,NaN,NaN,NaN
89,Immigrant,NaN,NaN,NaN
93,Immigrant,NaN,NaN,NaN
108,Immigrant,May,2024.0,NaN
1399,Immigrant,NaN,NaN,NaN
1427,Immigrant,NaN,NaN,NaN
2009,Immigrant,September,2028.0,NaN
2021,Immigrant,NaN,NaN,NaN
2022,Immigrant,NaN,NaN,NaN
2152,Immigrant,NaN,NaN,NaN
2165,Immigrant,NaN,NaN,NaN
2201,Immigrant,NaN,NaN,NaN
2256,Immigrant,April,2024.0,NaN
2260,Immigrant,October,2023.0,NaN
2265,Immigrant,NaN,NaN,NaN
2269,Immigrant,December,2024.0,NaN
2415,Immigrant,October,2023.0,NaN
3214,Immigrant,NaN,NaN,NaN
3242,Immigrant,December,2023.0,NaN
3599,Immigrant,NaN,NaN,NaN
4001,Immigrant,NaN,NaN,NaN

In [466]:
df.loc[~(df["Expected Month Returned"].isna()) & (df["Returned"]=="No") & (df["Reason for Leaving"]=="Immigrant") & ~(df["Expected Year Returned"].isna()) & (df["Return Reason"]=="N/A"), "Return Reason"] = "Unknown"

df.loc[(df["Expected Month Returned"].isna()) & (df["Returned"]=="No") & (df["Reason for Leaving"]=="Immigrant") & (df["Expected Year Returned"].isna()) & (df["Return Reason"]=="N/A"), "Expected Month Returned"] = "N/A"

df.loc[(df["Expected Month Returned"]=="N/A") & (df["Returned"]=="No") & (df["Reason for Leaving"]=="Immigrant") & (df["Expected Year Returned"].isna()) & (df["Return Reason"]=="N/A"), "Expected Year Returned"] = 0

df[(df['Returned'] == "No") & (df["Reason for Leaving"] == "Immigrant")][
    ["Reason for Leaving", "Expected Month Returned", "Expected Year Returned", "Return Reason"]]

,Reason for Leaving,Expected Month Returned,Expected Year Returned,Return Reason
0,Immigrant,NaN,NaN,NaN
1,Immigrant,NaN,NaN,NaN
2,Immigrant,NaN,NaN,NaN
5,Immigrant,NaN,NaN,NaN
12,Immigrant,NaN,NaN,NaN
13,Immigrant,NaN,NaN,NaN
19,Immigrant,NaN,NaN,NaN
20,Immigrant,NaN,NaN,NaN
23,Immigrant,June,2024.0,NaN
29,Immigrant,NaN,NaN,NaN
38,Immigrant,NaN,NaN,NaN
39,Immigrant,December,2023.0,NaN
44,Immigrant,NaN,NaN,NaN
45,Immigrant,NaN,NaN,NaN
46,Immigrant,NaN,NaN,NaN
47,Immigrant,NaN,NaN,NaN
52,Immigrant,NaN,NaN,NaN
53,Immigrant,NaN,NaN,NaN
54,Immigrant,NaN,NaN,NaN
56,Immigrant,NaN,NaN,NaN
59,Immigrant,NaN,NaN,NaN
60,Immigrant,NaN,NaN,NaN
64,Immigrant,NaN,NaN,NaN
85,Immigrant,NaN,NaN,NaN
86,Immigrant,NaN,NaN,NaN
88,Immigrant,NaN,NaN,NaN
89,Immigrant,NaN,NaN,NaN
93,Immigrant,NaN,NaN,NaN
108,Immigrant,May,2024.0,NaN
1399,Immigrant,NaN,NaN,NaN
1427,Immigrant,NaN,NaN,NaN
2009,Immigrant,September,2028.0,NaN
2021,Immigrant,NaN,NaN,NaN
2022,Immigrant,NaN,NaN,NaN
2152,Immigrant,NaN,NaN,NaN
2165,Immigrant,NaN,NaN,NaN
2201,Immigrant,NaN,NaN,NaN
2256,Immigrant,April,2024.0,NaN
2260,Immigrant,October,2023.0,NaN
2265,Immigrant,NaN,NaN,NaN
2269,Immigrant,December,2024.0,NaN
2415,Immigrant,October,2023.0,NaN
3214,Immigrant,NaN,NaN,NaN
3242,Immigrant,December,2023.0,NaN
3599,Immigrant,NaN,NaN,NaN
4001,Immigrant,NaN,NaN,NaN

In [467]:
df[df["Expected Month Returned"].isna()][['Reason for Leaving','Returned', "Month Returned", "Year Returned", "Return Reason", "Expected Month Returned", "Expected Year Returned"]]

,Reason for Leaving,Returned,Month Returned,Year Returned,Return Reason,Expected Month Returned,Expected Year Returned
0,Immigrant,No,NaN,NaN,NaN,NaN,NaN
1,Immigrant,No,NaN,NaN,NaN,NaN,NaN
2,Immigrant,No,NaN,NaN,NaN,NaN,NaN
5,Immigrant,No,NaN,NaN,NaN,NaN,NaN
6,Overseas Filipino Worker (OFW) with Contract,No,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
4294,Overseas Filipino Worker (OFW) with Contract,No,NaN,NaN,NaN,NaN,NaN
4295,Overseas Filipino Worker (OFW) with Contract,No,NaN,NaN,NaN,NaN,NaN
4296,Overseas Filipino Worker (OFW) with Contract,No,NaN,NaN,NaN,NaN,NaN
4297,Overseas Filipino Worker (OFW) with Contract,No,NaN,NaN,NaN,NaN,NaN
4303,Other OFW with no Contract,No,NaN,NaN,NaN,NaN,NaN

In [468]:
already_returned = df['Returned'] == 'Yes'

df.loc[already_returned & df['Expected Month Returned'].isna(), 'Expected Month Returned'] = np.nan
df.loc[already_returned & df['Expected Year Returned'].isna(), 'Expected Year Returned'] = np.nan


still_abroad = df['Returned'] == 'No'

df.loc[still_abroad & df['Expected Month Returned'].isna(), 'Expected Month Returned'] = np.nan
df.loc[still_abroad & df['Expected Year Returned'].isna(), 'Expected Year Returned'] = np.nan

df[['Reason for Leaving','Returned', "Month Returned", "Year Returned", "Return Reason", "Expected Month Returned", "Expected Year Returned"]]

,Reason for Leaving,Returned,Month Returned,Year Returned,Return Reason,Expected Month Returned,Expected Year Returned
0,Immigrant,No,NaN,NaN,NaN,NaN,NaN
1,Immigrant,No,NaN,NaN,NaN,NaN,NaN
2,Immigrant,No,NaN,NaN,NaN,NaN,NaN
3,Overseas Filipino Worker (OFW) with Contract,No,NaN,NaN,NaN,September,2027.0
4,Overseas Filipino Worker (OFW) with Contract,No,NaN,NaN,NaN,April,2025.0
...,...,...,...,...,...,...,...
4299,Overseas Filipino Worker (OFW) with Contract,No,NaN,NaN,NaN,June,2024.0
4300,Overseas Filipino Worker (OFW) with Contract,No,NaN,NaN,NaN,October,2027.0
4301,Overseas Filipino Worker (OFW) with Contract,No,NaN,NaN,NaN,May,2024.0
4302,Overseas Filipino Worker (OFW) with Contract,No,NaN,NaN,NaN,March,2024.0
4303,Other OFW with no Contract,No,NaN,NaN,NaN,NaN,NaN

In [469]:
df.isnull().sum()

Region                                      0
Relationship                                0
Sex                                         0
Age                                         0
Times Left the Country                      0
Month of Last Departure                     0
Year of Last Departure                      0
Marital Status                              9
Education Level                             0
Usual Work                                  0
Reason for Leaving                          0
Base                                        0
Country Stayed                              0
Expected Return (Months)                    0
Worked Abroad                               0
Work                                        0
Industry                                    0
Average Monthly Income                      0
Months Worked                               0
Returned                                    0
Month Returned                           2769
Year Returned                            2769
Return Reason                            2769
Expected Month Returned                  1911
Expected Year Returned                   1912
Remittance Received                         0
Cash Remittance                          1423
Mode of Remittance                       1440
Consumptions                                0
Investments                                 0
Savings                                     0
Gift/Donation                               0
Other                                       0
Consumptions Percent                     1440
Investments Percent                      1450
Savings Percent                          1440
Gift/Donation Percent                    1449
Other Percent                            1454
Returned Apr-Sep                            0
Cash Brought Home                        3508
Receive Goods/Products                      0
Total Imputed Value of Goods/Products    3898
dtype: int64

In [470]:
df[["Reason for Leaving","Worked Abroad", "Remittance Received", "Mode of Remittance", "Cash Remittance", "Consumptions", "Investments", "Savings", "Gift/Donation", "Other"]]

,Reason for Leaving,Worked Abroad,Remittance Received,Mode of Remittance,Cash Remittance,Consumptions,Investments,Savings,Gift/Donation,Other
0,Immigrant,Yes,With Remittance,Money Transer Service,180000.0,True,False,False,False,False
1,Immigrant,No,No Remittance,NaN,NaN,False,False,False,False,False
2,Immigrant,Yes,No Remittance,NaN,NaN,False,False,False,False,False
3,Overseas Filipino Worker (OFW) with Contract,Yes,With Remittance,Money Transer Service,20000.0,True,False,False,False,False
4,Overseas Filipino Worker (OFW) with Contract,Yes,With Remittance,Money Transer Service,40000.0,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
4299,Overseas Filipino Worker (OFW) with Contract,Yes,With Remittance,Bank,42000.0,True,False,False,False,False
4300,Overseas Filipino Worker (OFW) with Contract,Yes,With Remittance,Money Transer Service,36000.0,True,True,False,False,False
4301,Overseas Filipino Worker (OFW) with Contract,Yes,With Remittance,Money Transer Service,26000.0,True,False,False,False,False
4302,Overseas Filipino Worker (OFW) with Contract,Yes,With Remittance,Money Transer Service,26500.0,True,False,False,False,False
4303,Other OFW with no Contract,Yes,With Remittance,Money Transer Service,32500.0,True,False,False,False,False

In [471]:
no_remittance = df['Remittance Received'] == 'No Remittance'
df.loc[no_remittance & df['Mode of Remittance'].isna(), 'Mode of Remittance'] = 'N/A'
df[["Reason for Leaving","Worked Abroad", "Remittance Received", "Mode of Remittance", "Consumptions", "Investments", "Savings", "Gift/Donation", "Other"]]

,Reason for Leaving,Worked Abroad,Remittance Received,Mode of Remittance,Consumptions,Investments,Savings,Gift/Donation,Other
0,Immigrant,Yes,With Remittance,Money Transer Service,True,False,False,False,False
1,Immigrant,No,No Remittance,N/A,False,False,False,False,False
2,Immigrant,Yes,No Remittance,N/A,False,False,False,False,False
3,Overseas Filipino Worker (OFW) with Contract,Yes,With Remittance,Money Transer Service,True,False,False,False,False
4,Overseas Filipino Worker (OFW) with Contract,Yes,With Remittance,Money Transer Service,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...
4299,Overseas Filipino Worker (OFW) with Contract,Yes,With Remittance,Bank,True,False,False,False,False
4300,Overseas Filipino Worker (OFW) with Contract,Yes,With Remittance,Money Transer Service,True,True,False,False,False
4301,Overseas Filipino Worker (OFW) with Contract,Yes,With Remittance,Money Transer Service,True,False,False,False,False
4302,Overseas Filipino Worker (OFW) with Contract,Yes,With Remittance,Money Transer Service,True,False,False,False,False
4303,Other OFW with no Contract,Yes,With Remittance,Money Transer Service,True,False,False,False,False

In [472]:
df.isnull().sum()

Region                                      0
Relationship                                0
Sex                                         0
Age                                         0
Times Left the Country                      0
Month of Last Departure                     0
Year of Last Departure                      0
Marital Status                              9
Education Level                             0
Usual Work                                  0
Reason for Leaving                          0
Base                                        0
Country Stayed                              0
Expected Return (Months)                    0
Worked Abroad                               0
Work                                        0
Industry                                    0
Average Monthly Income                      0
Months Worked                               0
Returned                                    0
Month Returned                           2769
Year Returned                            2769
Return Reason                            2769
Expected Month Returned                  1911
Expected Year Returned                   1912
Remittance Received                         0
Cash Remittance                          1423
Mode of Remittance                          0
Consumptions                                0
Investments                                 0
Savings                                     0
Gift/Donation                               0
Other                                       0
Consumptions Percent                     1440
Investments Percent                      1450
Savings Percent                          1440
Gift/Donation Percent                    1449
Other Percent                            1454
Returned Apr-Sep                            0
Cash Brought Home                        3508
Receive Goods/Products                      0
Total Imputed Value of Goods/Products    3898
dtype: int64

In [473]:
no_remittance = df['Remittance Received'] == 'No Remittance'

df.loc[no_remittance & df['Cash Remittance'].isna(), 'Cash Remittance'] = 0

df[["Reason for Leaving","Worked Abroad", "Remittance Received", "Mode of Remittance", "Cash Remittance","Consumptions", "Investments", "Savings", "Gift/Donation", "Other"]]

,Reason for Leaving,Worked Abroad,Remittance Received,Mode of Remittance,Cash Remittance,Consumptions,Investments,Savings,Gift/Donation,Other
0,Immigrant,Yes,With Remittance,Money Transer Service,180000.0,True,False,False,False,False
1,Immigrant,No,No Remittance,N/A,0.0,False,False,False,False,False
2,Immigrant,Yes,No Remittance,N/A,0.0,False,False,False,False,False
3,Overseas Filipino Worker (OFW) with Contract,Yes,With Remittance,Money Transer Service,20000.0,True,False,False,False,False
4,Overseas Filipino Worker (OFW) with Contract,Yes,With Remittance,Money Transer Service,40000.0,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
4299,Overseas Filipino Worker (OFW) with Contract,Yes,With Remittance,Bank,42000.0,True,False,False,False,False
4300,Overseas Filipino Worker (OFW) with Contract,Yes,With Remittance,Money Transer Service,36000.0,True,True,False,False,False
4301,Overseas Filipino Worker (OFW) with Contract,Yes,With Remittance,Money Transer Service,26000.0,True,False,False,False,False
4302,Overseas Filipino Worker (OFW) with Contract,Yes,With Remittance,Money Transer Service,26500.0,True,False,False,False,False
4303,Other OFW with no Contract,Yes,With Remittance,Money Transer Service,32500.0,True,False,False,False,False

In [474]:

df[["Remittance Received", "Mode of Remittance", "Cash Remittance", "Consumptions Percent", "Investments Percent", "Savings Percent", "Gift/Donation Percent", "Other Percent"]]

,Remittance Received,Mode of Remittance,Cash Remittance,Consumptions Percent,Investments Percent,Savings Percent,Gift/Donation Percent,Other Percent
0,With Remittance,Money Transer Service,180000.0,100.0,0.0,0.0,0.0,0.0
1,No Remittance,N/A,0.0,NaN,NaN,NaN,NaN,NaN
2,No Remittance,N/A,0.0,NaN,NaN,NaN,NaN,NaN
3,With Remittance,Money Transer Service,20000.0,100.0,0.0,0.0,0.0,0.0
4,With Remittance,Money Transer Service,40000.0,100.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
4299,With Remittance,Bank,42000.0,100.0,0.0,0.0,0.0,0.0
4300,With Remittance,Money Transer Service,36000.0,50.0,50.0,0.0,0.0,0.0
4301,With Remittance,Money Transer Service,26000.0,100.0,0.0,0.0,0.0,0.0
4302,With Remittance,Money Transer Service,26500.0,100.0,0.0,0.0,0.0,0.0
4303,With Remittance,Money Transer Service,32500.0,100.0,0.0,0.0,0.0,0.0

In [475]:
no_remittance = df['Remittance Received'] == 'No Remittance'

percent_columns = [
    'Consumptions Percent',
    'Investments Percent',
    'Savings Percent',
    'Gift/Donation Percent',
    'Other Percent'
]

df.loc[no_remittance, percent_columns] = 0

df[["Remittance Received", "Mode of Remittance", "Cash Remittance", "Consumptions Percent", "Investments Percent", "Savings Percent", "Gift/Donation Percent", "Other Percent"]]

,Remittance Received,Mode of Remittance,Cash Remittance,Consumptions Percent,Investments Percent,Savings Percent,Gift/Donation Percent,Other Percent
0,With Remittance,Money Transer Service,180000.0,100.0,0.0,0.0,0.0,0.0
1,No Remittance,N/A,0.0,0.0,0.0,0.0,0.0,0.0
2,No Remittance,N/A,0.0,0.0,0.0,0.0,0.0,0.0
3,With Remittance,Money Transer Service,20000.0,100.0,0.0,0.0,0.0,0.0
4,With Remittance,Money Transer Service,40000.0,100.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
4299,With Remittance,Bank,42000.0,100.0,0.0,0.0,0.0,0.0
4300,With Remittance,Money Transer Service,36000.0,50.0,50.0,0.0,0.0,0.0
4301,With Remittance,Money Transer Service,26000.0,100.0,0.0,0.0,0.0,0.0
4302,With Remittance,Money Transer Service,26500.0,100.0,0.0,0.0,0.0,0.0
4303,With Remittance,Money Transer Service,32500.0,100.0,0.0,0.0,0.0,0.0

In [476]:
df[df["Investments Percent"].isna()][["Remittance Received", "Mode of Remittance", "Cash Remittance", "Consumptions Percent", "Investments Percent", "Savings Percent", "Gift/Donation Percent", "Other Percent"]]

,Remittance Received,Mode of Remittance,Cash Remittance,Consumptions Percent,Investments Percent,Savings Percent,Gift/Donation Percent,Other Percent
2178,With Remittance,Money Transer Service,60000.0,100.0,NaN,0.0,NaN,NaN
2453,With Remittance,Money Transer Service,60000.0,60.0,NaN,40.0,0.0,0.0
2850,With Remittance,Money Transer Service,60000.0,100.0,NaN,0.0,NaN,NaN
3019,With Remittance,Money Transer Service,20000.0,100.0,NaN,0.0,NaN,NaN
3204,With Remittance,Bank,230000.0,75.0,NaN,25.0,NaN,NaN
3205,With Remittance,Bank,60000.0,20.0,NaN,80.0,NaN,NaN
3448,With Remittance,Money Transer Service,90000.0,80.0,NaN,20.0,NaN,NaN
3757,With Remittance,Money Transer Service,18000.0,100.0,NaN,0.0,NaN,NaN
4156,With Remittance,Money Transer Service,30000.0,100.0,NaN,0.0,NaN,NaN
4187,With Remittance,Bank,30000.0,50.0,NaN,0.0,50.0,NaN

In [477]:
percent_columns = [
    'Consumptions Percent',
    'Investments Percent',
    'Savings Percent',
    'Gift/Donation Percent',
    'Other Percent'
]

df[percent_columns] = df[percent_columns].fillna(0)

In [478]:
df[["Remittance Received", "Mode of Remittance", "Cash Remittance", "Consumptions Percent", "Investments Percent", "Savings Percent", "Gift/Donation Percent", "Other Percent", "Cash Brought Home"]]

,Remittance Received,Mode of Remittance,Cash Remittance,Consumptions Percent,Investments Percent,Savings Percent,Gift/Donation Percent,Other Percent,Cash Brought Home
0,With Remittance,Money Transer Service,180000.0,100.0,0.0,0.0,0.0,0.0,NaN
1,No Remittance,N/A,0.0,0.0,0.0,0.0,0.0,0.0,NaN
2,No Remittance,N/A,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3,With Remittance,Money Transer Service,20000.0,100.0,0.0,0.0,0.0,0.0,20000.0
4,With Remittance,Money Transer Service,40000.0,100.0,0.0,0.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...
4299,With Remittance,Bank,42000.0,100.0,0.0,0.0,0.0,0.0,NaN
4300,With Remittance,Money Transer Service,36000.0,50.0,50.0,0.0,0.0,0.0,NaN
4301,With Remittance,Money Transer Service,26000.0,100.0,0.0,0.0,0.0,0.0,NaN
4302,With Remittance,Money Transer Service,26500.0,100.0,0.0,0.0,0.0,0.0,NaN
4303,With Remittance,Money Transer Service,32500.0,100.0,0.0,0.0,0.0,0.0,NaN

In [479]:
df['Cash Brought Home'] = df['Cash Brought Home'].fillna(0)
df[["Remittance Received", "Mode of Remittance", "Cash Remittance", "Consumptions Percent", "Investments Percent", "Savings Percent", "Gift/Donation Percent", "Other Percent", "Cash Brought Home"]]

,Remittance Received,Mode of Remittance,Cash Remittance,Consumptions Percent,Investments Percent,Savings Percent,Gift/Donation Percent,Other Percent,Cash Brought Home
0,With Remittance,Money Transer Service,180000.0,100.0,0.0,0.0,0.0,0.0,0.0
1,No Remittance,N/A,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,No Remittance,N/A,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,With Remittance,Money Transer Service,20000.0,100.0,0.0,0.0,0.0,0.0,20000.0
4,With Remittance,Money Transer Service,40000.0,100.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
4299,With Remittance,Bank,42000.0,100.0,0.0,0.0,0.0,0.0,0.0
4300,With Remittance,Money Transer Service,36000.0,50.0,50.0,0.0,0.0,0.0,0.0
4301,With Remittance,Money Transer Service,26000.0,100.0,0.0,0.0,0.0,0.0,0.0
4302,With Remittance,Money Transer Service,26500.0,100.0,0.0,0.0,0.0,0.0,0.0
4303,With Remittance,Money Transer Service,32500.0,100.0,0.0,0.0,0.0,0.0,0.0

In [480]:
df.isnull().sum()

Region                                      0
Relationship                                0
Sex                                         0
Age                                         0
Times Left the Country                      0
Month of Last Departure                     0
Year of Last Departure                      0
Marital Status                              9
Education Level                             0
Usual Work                                  0
Reason for Leaving                          0
Base                                        0
Country Stayed                              0
Expected Return (Months)                    0
Worked Abroad                               0
Work                                        0
Industry                                    0
Average Monthly Income                      0
Months Worked                               0
Returned                                    0
Month Returned                           2769
Year Returned                            2769
Return Reason                            2769
Expected Month Returned                  1911
Expected Year Returned                   1912
Remittance Received                         0
Cash Remittance                             0
Mode of Remittance                          0
Consumptions                                0
Investments                                 0
Savings                                     0
Gift/Donation                               0
Other                                       0
Consumptions Percent                        0
Investments Percent                         0
Savings Percent                             0
Gift/Donation Percent                       0
Other Percent                               0
Returned Apr-Sep                            0
Cash Brought Home                           0
Receive Goods/Products                      0
Total Imputed Value of Goods/Products    3898
dtype: int64

In [481]:
df.loc[df["Receive Goods/Products"] == "No", "Total Imputed Value of Goods/Products"] =0
df[['Receive Goods/Products', "Total Imputed Value of Goods/Products"]]

     Receive Goods/Products  Total Imputed Value of Goods/Products
0                       Yes                                55000.0
1                        No                                    0.0
2                        No                                    0.0
3                       Yes                                30000.0
4                        No                                    0.0
...                     ...                                    ...
4299                     No                                    0.0
4300                     No                                    0.0
4301                     No                                    0.0
4302                    Yes                                17000.0
4303                     No                                    0.0

[4302 rows x 2 columns]

In [482]:
df[df["Total Imputed Value of Goods/Products"].isna()][['Receive Goods/Products', "Total Imputed Value of Goods/Products"]]

     Receive Goods/Products  Total Imputed Value of Goods/Products
3301                    Yes                                    NaN

In [483]:
needs_imputation = ((df["Total Imputed Value of Goods/Products"].isna()) | (df["Total Imputed Value of Goods/Products"] == 0)) & (df["Receive Goods/Products"] == "Yes")
df.loc[needs_imputation, "Total Imputed Value of Goods/Products"] = df[df["Receive Goods/Products"]=="Yes"]["Total Imputed Value of Goods/Products"].median()

In [484]:
df.to_csv("./dataset/SOF PUF 2023 - Clean v2.CSV", index=False)