In [1]:
! pip install pandas numpy matplotlib scikit-learn seaborn

Requirement already satisfied: pandas in .\.venv\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy in .\.venv\Lib\site-packages (2.4.6)
Requirement already satisfied: matplotlib in .\.venv\Lib\site-packages (3.10.9)
Requirement already satisfied: scikit-learn in .\.venv\Lib\site-packages (1.8.0)
Requirement already satisfied: seaborn in .\.venv\Lib\site-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\.venv\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in .\.venv\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in .\.venv\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in .\.venv\Lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in .\.venv\Lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in .\.venv\Lib\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in .\.venv\Lib\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in .\.venv\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: scipy>=1.10.0 in .\.venv\Lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in .\.venv\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in .\.venv\Lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in .\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import numpy as np
import seaborn as sb
import  sklearn as sk
import matplotlib as mp

In [3]:
df = pd.read_csv("./dataset/SOF PUF 2023.CSV", encoding = "ISO-8859-1")
df.head()

,RREG,RHHNUM,RQ1_LNO,RQ2_REL,RQ3_SEX,RQ4_AGE,RQ5_TMSLEFT,RQ6M_DTLEFT,RQ6Y_DTLEFT,RQ7_MSTAT,...,RQ264P_GIFT,RQ265P_OTHERS,RQ27_RET6MOS,RQ28_CASHHOME,RQ29_INKIND,RQ30_KINDAMT,RSWGT,RP6M_IND,RSVYYR,RPRRCD
0,1,1,81,8,1,65,1,3,2023,2,...,000,000,2,,1,00055000,463.1271,,2023,2800
1,1,1,82,8,2,72,1,3,2023,2,...,,,2,,2,,463.1271,,2023,2800
2,1,1,83,8,2,30,1,3,2023,1,...,,,2,,2,,463.1271,,2023,2800
3,1,2,4,3,2,42,2,9,2023,3,...,000,000,1,0020000,1,00030000,456.8271,1,2023,2800
4,1,3,2,2,2,43,1,4,2023,2,...,000,000,2,,2,,456.8271,1,2023,2800

In [4]:
df_clean = pd.DataFrame()
df_clean.head()

Empty DataFrame
Columns: []
Index: []

In [5]:
df["RREG"].value_counts()

# Formatting RREG
rreg_mapping = {
    13: "NCR",
    14: "CAR",
    1: "Ilocos",
    2: "Cagayan Valley",
    3: "Central Luzon",
    4: "CALABARZON",
    17: "MIMAROPA",
    5: "Bicol",
    6: "Western Visayas",
    7: "Central Visayas",
    8: "Eastern Visayas",
    9: "Zamboanga Peninsula",
    10: "Northern Mindanao",
    11: "Davao",
    12: "SOCCSKSARGEN",
    16: "Caraga",
    19: "ARMM"
}

df_clean["Region"] = df['RREG'].map(rreg_mapping)
df_clean["Region"].value_counts()

Region
NCR                    580
Central Luzon          421
CALABARZON             401
Western Visayas        367
Ilocos                 292
Cagayan Valley         265
Central Visayas        261
CAR                    207
Northern Mindanao      194
Eastern Visayas        193
SOCCSKSARGEN           191
Bicol                  169
Caraga                 169
ARMM                   167
Davao                  163
MIMAROPA               150
Zamboanga Peninsula    114
Name: count, dtype: int64

In [6]:
df["RQ1_LNO"].value_counts()
# nothing significant based on the meta data.

RQ1_LNO
2     1602
3      781
4      494
1      452
5      309
6      206
81     186
7      116
8       63
9       34
10      17
82      16
11      14
12       5
83       3
13       2
84       1
15       1
18       1
16       1
Name: count, dtype: int64

In [7]:
df["RQ2_REL"].value_counts()

# Formatting Relationship
rq2_rel_mapping = {
    1: "Head",
    2: "Spouse",
    3: "Child",
    4: "Sibling",
    5: "Children's Spouse",
    6: "Grandchild",
    7: "Parent",
    8: "Other"
}

df_clean["Relationship"] = df["RQ2_REL"].map(rq2_rel_mapping)
df_clean["Relationship"].value_counts()

Relationship
Spouse               1592
Child                1496
Head                  452
Children's Spouse     286
Sibling               178
Other                 131
Parent                127
Grandchild             42
Name: count, dtype: int64

In [8]:
df["RQ3_SEX"].value_counts()

rq3_sex_mapping = {
    1: "Male",
    2: "Female",
}

df_clean["Sex"] = df["RQ3_SEX"].map(rq3_sex_mapping)
df_clean["Sex"].value_counts()

Sex
Female    2520
Male      1784
Name: count, dtype: int64

In [9]:
df_clean["Age"] = df["RQ4_AGE"]
df_clean.head()

   Region Relationship     Sex  Age
0  Ilocos        Other    Male   65
1  Ilocos        Other  Female   72
2  Ilocos        Other  Female   30
3  Ilocos        Child  Female   42
4  Ilocos       Spouse  Female   43

In [10]:
df['RQ5_TMSLEFT'].value_counts()
df_clean["Times Left the Country"] = df["RQ5_TMSLEFT"]
df_clean.head()

   Region Relationship     Sex  Age  Times Left the Country
0  Ilocos        Other    Male   65                       1
1  Ilocos        Other  Female   72                       1
2  Ilocos        Other  Female   30                       1
3  Ilocos        Child  Female   42                       2
4  Ilocos       Spouse  Female   43                       1

In [11]:
df["RQ6M_DTLEFT"].value_counts()

rq6m_dtleft = {
    1: "January",
    2: "February",
    3: "March",
    4: "April",
    5: "May",
    6: "June",
    7: "July",
    8: "August",
    9: "September",
    10: "October",
    11: "November",
    12: "December"
}

df_clean["Month of Last Departure"] = df['RQ6M_DTLEFT'].map(rq6m_dtleft)
df_clean["Month of Last Departure"].value_counts()

Month of Last Departure
August       426
September    410
December     383
July         380
June         369
January      363
March        362
May          359
October      358
February     311
November     292
April        291
Name: count, dtype: int64

In [12]:
df["RQ6Y_DTLEFT"].value_counts()

df_clean["Year of Last Departure"] = df["RQ6Y_DTLEFT"]
df_clean.head()

,Region,Relationship,Sex,Age,Times Left the Country,Month of Last Departure,Year of Last Departure
0,Ilocos,Other,Male,65,1,March,2023
1,Ilocos,Other,Female,72,1,March,2023
2,Ilocos,Other,Female,30,1,March,2023
3,Ilocos,Child,Female,42,2,September,2023
4,Ilocos,Spouse,Female,43,1,April,2023

In [13]:
df["RQ7_MSTAT"].value_counts()

df["RQ7_MSTAT"].info()

rq7_mstat_mapping = {
    "1": "Single",
    "2": "Married/Living Together",
    "3": "Widowed",
    "4": "Divorced/Separated",
    "5": "Annulled",
    "6": "Unknown"
}

df_clean["Marital Status"] = df["RQ7_MSTAT"].map(rq7_mstat_mapping).fillna("Unknown")
df_clean["Marital Status"].value_counts()

<class 'pandas.Series'>
RangeIndex: 4304 entries, 0 to 4303
Series name: RQ7_MSTAT
Non-Null Count  Dtype
--------------  -----
4304 non-null   str
dtypes: str(1)
memory usage: 33.8 KB

Marital Status
Married/Living Together    2637
Single                     1185
Divorced/Separated          340
Widowed                     132
Unknown                       9
Annulled                      1
Name: count, dtype: int64

In [98]:
df['RQ8_HGRADE'].value_counts()

df["RQ8_HGRADE"].info()

rq8_hgrade_mapping = {
    1: "Elementary Undergraduate",
    2: "Elementary Graduate",
    3: "Junior High Undergraduate",
    4: "Junior High Graduate",
    5: "Senior High Undergraduate",
    6: "Senior High Graduate",
    7: "Post Secondary Undergraduate",
    8: "Post-Secondary Non-Tertiary/Technical-Vocational Graduate",
    9: "College Undergraduate",
    10: "College Graduate",
    11: "Post Baccalaureate/ Post Graduate"
}

df_clean["Education Level"] = df["RQ8_HGRADE"].str.strip().replace("",12).astype(int).map(rq8_hgrade_mapping)
df_clean["Education Level"].value_counts()

<class 'pandas.Series'>
RangeIndex: 4304 entries, 0 to 4303
Series name: RQ8_HGRADE
Non-Null Count  Dtype
--------------  -----
4304 non-null   str
dtypes: str(1)
memory usage: 33.8 KB

Education Level
College Graduate                                             1722
Junior High Graduate                                         1170
College Undergraduate                                         524
Post-Secondary Non-Tertiary/Technical-Vocational Graduate     262
Junior High Undergraduate                                     191
Elementary Graduate                                           106
Post Baccalaureate/ Post Graduate                              78
Elementary Undergraduate                                       74
Senior High Graduate                                           10
Senior High Undergraduate                                       6
Post Secondary Undergraduate                                    2
Name: count, dtype: int64

In [15]:
df['RQ9_2DGT'].value_counts()

rq9_2dgt_mapping = {
    # Managers (11 to 14)
    "11": "Managers", "12": "Managers", "13": "Managers", "14": "Managers",

    # Professionals (21 to 26)
    "21": "Professionals", "22": "Professionals", "23": "Professionals",
    "24": "Professionals", "25": "Professionals", "26": "Professionals",

    # Technicians and Associate Professionals (31 to 35)
    "31": "Technicians and Associate Professionals", "32": "Technicians and Associate Professionals",
    "33": "Technicians and Associate Professionals", "34": "Technicians and Associate Professionals",
    "35": "Technicians and Associate Professionals",

    # Clerical Support Workers (41 to 44)
    "41": "Clerical Support Workers", "42": "Clerical Support Workers",
    "43": "Clerical Support Workers", "44": "Clerical Support Workers",

    # Service and Sales Workers (51 to 54)
    "51": "Service and Sales Workers", "52": "Service and Sales Workers",
    "53": "Service and Sales Workers", "54": "Service and Sales Workers",

    # Skilled Agricultural, Forestry and Fishery Workers (61 to 63)
    "61": "Skilled Agricultural, Forestry and Fishery Workers",
    "62": "Skilled Agricultural, Forestry and Fishery Workers",
    "63": "Skilled Agricultural, Forestry and Fishery Workers",

    # Craft and Related Trades Workers (71 to 75)
    "71": "Craft and Related Trades Workers", "72": "Craft and Related Trades Workers",
    "73": "Craft and Related Trades Workers", "74": "Craft and Related Trades Workers",
    "75": "Craft and Related Trades Workers",

    # Plant and Machine Operators and Assemblers (81 to 83)
    "81": "Plant and Machine Operators and Assemblers",
    "82": "Plant and Machine Operators and Assemblers",
    "83": "Plant and Machine Operators and Assemblers",

    # Elementary Occupations (91 to 96)
    "91": "Elementary Occupations", "92": "Elementary Occupations",
    "93": "Elementary Occupations", "94": "Elementary Occupations",
    "95": "Elementary Occupations", "96": "Elementary Occupations",

    # Armed Forces Occupations (01 to 03)
    "01": "Armed Forces Occupations", "02": "Armed Forces Occupations", "03": "Armed Forces Occupations",

    # Non-gainful occupations (09)
    "09": "Non-gainful occupations"
}

df_clean["Usual Work"] = df["RQ9_2DGT"].map(rq9_2dgt_mapping)
df_clean["Usual Work"].value_counts()

Usual Work
Non-gainful occupations                               929
Service and Sales Workers                             849
Elementary Occupations                                774
Professionals                                         408
Clerical Support Workers                              259
Technicians and Associate Professionals               238
Skilled Agricultural, Forestry and Fishery Workers    225
Plant and Machine Operators and Assemblers            212
Managers                                              210
Craft and Related Trades Workers                      195
Armed Forces Occupations                                1
Name: count, dtype: int64

In [16]:
df["RQ10_REASON"].info()
df['RQ10_REASON'].value_counts()

rq10_reason_mapping = {
    1: "Overseas Filipino Worker (OFW) with Contract",
    2: "Other OFW with no Contract",
    3: "Work with Philippine Embassy/Consulate Abroad",
    4: "Tourist",
    5: "Student",
    6: "Immigrant",
    7: "Official Mission",
    8: "Others, specify"
}

df_clean["Reason for Leaving"] = df["RQ10_REASON"].map(rq10_reason_mapping)
df_clean["Reason for Leaving"].value_counts()

<class 'pandas.Series'>
RangeIndex: 4304 entries, 0 to 4303
Series name: RQ10_REASON
Non-Null Count  Dtype
--------------  -----
4304 non-null   int64
dtypes: int64(1)
memory usage: 33.8 KB

Reason for Leaving
Overseas Filipino Worker (OFW) with Contract     3485
Tourist                                           601
Other OFW with no Contract                         90
Immigrant                                          47
Others, specify                                    47
Student                                            24
Official Mission                                    6
Work with Philippine Embassy/Consulate Abroad       4
Name: count, dtype: int64

In [17]:
df["RQ11_BASE"].value_counts()
df["RQ11_BASE"].info()


rq11_base_mapping = {
    "1" : "Land-based",
    "2" : "Sea-based",
    "3" : "Others"
}

df_clean["Base"] = df["RQ11_BASE"].map(rq11_base_mapping)
df_clean["Base"].value_counts()

<class 'pandas.Series'>
RangeIndex: 4304 entries, 0 to 4303
Series name: RQ11_BASE
Non-Null Count  Dtype
--------------  -----
4304 non-null   str
dtypes: str(1)
memory usage: 33.8 KB

Base
Land-based    2975
Sea-based      597
Others           3
Name: count, dtype: int64

In [18]:
df["RQ12_CTRY"].info()

rq12_ctry_mapping = {
    # Africa
    100: "Africa",

    # East Asia
    211: "Hongkong",
    212: "Japan",
    213: "Taiwan",
    214: "Other Countries in East Asia",

    # Southeast and South Central Asia
    221: "Malaysia",
    222: "Singapore",
    223: "Other Countries in SE & SC Asia",

    # Western Asia
    231: "Kuwait",
    232: "Qatar",
    233: "Saudi Arabia",
    234: "United Arab Emirates",
    235: "Other Countries in Western Asia",

    # Other Continents and Regions
    300: "Australia",
    400: "Europe",
    500: "North and South America",
    600: "Other Countries"
}

df_clean["Country Stayed"] = df["RQ12_CTRY"].map(rq12_ctry_mapping)
df_clean["Country Stayed"].value_counts()

<class 'pandas.Series'>
RangeIndex: 4304 entries, 0 to 4303
Series name: RQ12_CTRY
Non-Null Count  Dtype
--------------  -----
4304 non-null   int64
dtypes: int64(1)
memory usage: 33.8 KB

Country Stayed
Saudi Arabia                       785
United Arab Emirates               456
North and South America            416
Europe                             351
Hongkong                           291
Kuwait                             277
Japan                              273
Singapore                          260
Qatar                              216
Other Countries in East Asia       192
Taiwan                             175
Australia                          163
Other Countries in Western Asia    147
Other Countries in SE & SC Asia    137
Malaysia                           102
Africa                              49
Other Countries                     14
Name: count, dtype: int64

In [19]:
df['RQ13_RETURN'].value_counts()

df_clean["Expected Return (Months)"] = df["RQ13_RETURN"]
df_clean["Expected Return (Months)"].value_counts()

Expected Return (Months)
24    972
88    379
0     325
36    310
1     188
     ...
76      1
85      1
69      1
71      1
66      1
Name: count, Length: 72, dtype: int64

In [20]:
df['RQ14_INDWORK'].value_counts()
df["RQ14_INDWORK"].info()

rq14_indwork_mapping = {
    1: "Yes",
    2: "No"
}

df_clean["Worked Abroad"] = df["RQ14_INDWORK"].map(rq14_indwork_mapping)
df_clean["Worked Abroad"].value_counts()

<class 'pandas.Series'>
RangeIndex: 4304 entries, 0 to 4303
Series name: RQ14_INDWORK
Non-Null Count  Dtype
--------------  -----
4304 non-null   int64
dtypes: int64(1)
memory usage: 33.8 KB

Worked Abroad
Yes    3612
No      692
Name: count, dtype: int64

In [21]:
df["RQ15_2DGT"].info()
df["RQ15_2DGT"].value_counts()


df_clean["Work"] = df["RQ15_2DGT"].map(rq9_2dgt_mapping)
df_clean["Work"].value_counts()

<class 'pandas.Series'>
RangeIndex: 4304 entries, 0 to 4303
Series name: RQ15_2DGT
Non-Null Count  Dtype
--------------  -----
4304 non-null   str
dtypes: str(1)
memory usage: 33.8 KB

Work
Elementary Occupations                                1678
Service and Sales Workers                              483
Plant and Machine Operators and Assemblers             431
Professionals                                          293
Technicians and Associate Professionals                292
Craft and Related Trades Workers                       221
Clerical Support Workers                               116
Managers                                                74
Skilled Agricultural, Forestry and Fishery Workers      24
Name: count, dtype: int64

In [22]:
df['RQ16_2DGT'].info()
df['RQ16_2DGT'].value_counts()

q16_ind_mapping = {
    # Agriculture, Forestry and Fishing
    1: "Agriculture and Forestry",
    2: "Agriculture and Forestry",
    3: "Fishing and Aquaculture",

    # Industry
    5: "Mining and Quarrying",
    6: "Mining and Quarrying",
    7: "Mining and Quarrying",
    8: "Mining and Quarrying",
    9: "Mining and Quarrying",

    # Manufacturing
    **{i: "Manufacturing" for i in range(10, 34)},

    # Utilities
    35: "Electricity, Gas, Steam and Air Conditioning Supply",
    36: "Water Supply; Sewerage, Waste Management and Remediation Activities",
    37: "Water Supply; Sewerage, Waste Management and Remediation Activities",
    38: "Water Supply; Sewerage, Waste Management and Remediation Activities",
    39: "Water Supply; Sewerage, Waste Management and Remediation Activities",

    # Construction
    41: "Construction",
    42: "Construction",
    43: "Construction",

    # Trade
    45: "Wholesale and Retail Trade; Repair of Motor Vehicles and Motorcycles",
    46: "Wholesale and Retail Trade; Repair of Motor Vehicles and Motorcycles",
    47: "Wholesale and Retail Trade; Repair of Motor Vehicles and Motorcycles",

    # Transport
    49: "Transportation and Storage",
    50: "Transportation and Storage",
    51: "Transportation and Storage",
    52: "Transportation and Storage",
    53: "Transportation and Storage",

    # Accommodation & Food
    55: "Accommodation and Food Service Activities",
    56: "Accommodation and Food Service Activities",

    # Information & Communication
    58: "Information and Communication",
    59: "Information and Communication",
    60: "Information and Communication",
    61: "Information and Communication",
    62: "Information and Communication",
    63: "Information and Communication",

    # Finance
    64: "Financial and Insurance Activities",
    65: "Financial and Insurance Activities",
    66: "Financial and Insurance Activities",

    # Real Estate
    68: "Real Estate Activities",

    # Professional Services
    69: "Professional, Scientific and Technical Activities",
    70: "Professional, Scientific and Technical Activities",
    71: "Professional, Scientific and Technical Activities",
    72: "Professional, Scientific and Technical Activities",
    73: "Professional, Scientific and Technical Activities",
    74: "Professional, Scientific and Technical Activities",
    75: "Professional, Scientific and Technical Activities",

    # Administrative Support
    77: "Administrative and Support Service Activities",
    78: "Administrative and Support Service Activities",
    79: "Administrative and Support Service Activities",
    80: "Administrative and Support Service Activities",
    81: "Administrative and Support Service Activities",
    82: "Administrative and Support Service Activities",

    # Public Administration
    84: "Public Administration and Defense; Compulsory Social Security",

    # Education
    85: "Education",

    # Health
    86: "Human Health and Social Work Activities",
    87: "Human Health and Social Work Activities",
    88: "Human Health and Social Work Activities",

    # Arts & Recreation
    90: "Arts, Entertainment and Recreation",
    91: "Arts, Entertainment and Recreation",
    92: "Arts, Entertainment and Recreation",
    93: "Arts, Entertainment and Recreation",

    # Other Services
    94: "Other Service Activities",
    95: "Other Service Activities",
    96: "Other Service Activities",

    # Households
    97: "Activities of Households as Employers",
    98: "Activities of Households as Employers",

    # Extraterritorial Organizations
    99: "Activities of Extraterritorial Organizations and Bodies",
}

df_clean["Industry"] = df['RQ16_2DGT'].str.strip().replace("", 100).astype(int).map(q16_ind_mapping)
df_clean["Industry"].value_counts()

<class 'pandas.Series'>
RangeIndex: 4304 entries, 0 to 4303
Series name: RQ16_2DGT
Non-Null Count  Dtype
--------------  -----
4304 non-null   str
dtypes: str(1)
memory usage: 33.8 KB

Industry
Other Service Activities                                                1567
Transportation and Storage                                               530
Manufacturing                                                            358
Accommodation and Food Service Activities                                260
Human Health and Social Work Activities                                  206
Construction                                                             193
Wholesale and Retail Trade; Repair of Motor Vehicles and Motorcycles     154
Administrative and Support Service Activities                             77
Education                                                                 67
Agriculture and Forestry                                                  40
Professional, Scientific and Technical Activities                         35
Information and Communication                                             32
Fishing and Aquaculture                                                   29
Electricity, Gas, Steam and Air Conditioning Supply                       13
Public Administration and Defense; Compulsory Social Security             13
Arts, Entertainment and Recreation                                        13
Financial and Insurance Activities                                        11
Mining and Quarrying                                                       6
Real Estate Activities                                                     5
Water Supply; Sewerage, Waste Management and Remediation Activities        3
Name: count, dtype: int64

In [23]:
df_clean["Average Monthly Income"] = pd.to_numeric(df["RQ17_AVEMINC"].astype(str).str.strip(), errors="coerce").astype("Int64")
df_clean["Average Monthly Income"].head()

0    168960
1      <NA>
2     50000
3     25000
4     32000
Name: Average Monthly Income, dtype: Int64

In [24]:
df_clean["Months Worked"] = pd.to_numeric(df["RQ18_NOMONTH"].astype(str).str.strip(), errors="coerce").astype("Int64")
df_clean["Months Worked"].head()

0       6
1    <NA>
2       6
3      59
4       5
Name: Months Worked, dtype: Int64

In [25]:
df_clean["Returned"] = df["RQ19_RET"].map(rq14_indwork_mapping)
df_clean["Returned"].value_counts()

Returned
No     2771
Yes    1533
Name: count, dtype: int64

In [26]:
df_clean["Month Returned"] = df["RQ20M_DTRET"].astype(str).str.strip().replace("", 13).astype(int).map(rq6m_dtleft)
df_clean["Month Returned"].value_counts()

Month Returned
September    248
August       219
July         160
June         137
December     117
May          110
April        103
March         91
January       90
November      88
February      88
October       82
Name: count, dtype: int64

In [27]:
df_clean["Year Returned"] = pd.to_numeric(df["RQ20Y_DTRET"].astype(str).str.strip(), errors="coerce").astype("Int64")
df_clean["Year Returned"].value_counts()

Year Returned
2023    804
2022    293
2019    167
2021    120
2020    117
2018     32
Name: count, dtype: Int64

In [28]:
df['RQ21_REASON'].info()
df['RQ21_REASON'].value_counts()

rq21_reason_mapping = {
    1: "Visit",
    2: "End of Contract",
    3: "Covid-19",
    4: "Other"
}

df_clean["Return Reason"] = df["RQ21_REASON"].astype(str).str.strip().replace("", 5).astype(int).map(rq21_reason_mapping)
df_clean["Return Reason"].value_counts()

<class 'pandas.Series'>
RangeIndex: 4304 entries, 0 to 4303
Series name: RQ21_REASON
Non-Null Count  Dtype
--------------  -----
4304 non-null   str
dtypes: str(1)
memory usage: 33.8 KB

Return Reason
End of Contract    775
Other              592
Visit              132
Covid-19            34
Name: count, dtype: int64

In [29]:
df_clean["Expected Month Returned"] = df["RQ22M_DTEXP"].astype(str).str.strip().replace("", 13).astype(int).map(rq6m_dtleft)
df_clean["Expected Month Returned"].value_counts()

Expected Month Returned
December     401
March        200
January      199
October      197
May          180
September    179
August       176
June         175
November     174
April        172
July         170
February     170
Name: count, dtype: int64

In [49]:
df_clean["Expected Year Returned"] = pd.to_numeric(df["RQ22Y_DTEXP"].astype(str).str.strip(), errors="coerce").astype("Int64")
df_clean["Expected Year Returned"] = df_clean["Expected Year Returned"].replace(8888, np.nan)
df_clean["Expected Year Returned"]

0       <NA>
1       <NA>
2       <NA>
3       2027
4       2025
        ...
4299    2024
4300    2027
4301    2024
4302    2024
4303    <NA>
Name: Expected Year Returned, Length: 4304, dtype: Int64

In [31]:
df["RQ23_CASHREM"].value_counts()
df["RQ23_CASHREM"].info()

rq23_cashrem_mapping = {
    1: "With Remittance",
    2: "No Remittance",
    9: "Not Reported"
}

df_clean["Remittance Received"] = df["RQ23_CASHREM"].map(rq23_cashrem_mapping)
df_clean["Remittance Received"].value_counts()

<class 'pandas.Series'>
RangeIndex: 4304 entries, 0 to 4303
Series name: RQ23_CASHREM
Non-Null Count  Dtype
--------------  -----
4304 non-null   int64
dtypes: int64(1)
memory usage: 33.8 KB

Remittance Received
With Remittance    2863
No Remittance      1441
Name: count, dtype: int64

In [47]:
df_clean["Cash Remittance"] = pd.to_numeric(df['RQ24_CASHAMT'].astype(str).str.strip(), errors="coerce").astype("float64")
df_clean["Cash Remittance"]

0       180000.0
1            NaN
2            NaN
3        20000.0
4        40000.0
          ...
4299     42000.0
4300     36000.0
4301     26000.0
4302     26500.0
4303     32500.0
Name: Cash Remittance, Length: 4304, dtype: float64

In [44]:

rq25_mode_mapping = {
    1: "Bank",
    2: "Agency/Local Office",
    3: "Friends/Co-workers",
    4: "Door-to-Door",
    5: "Money Transer Service",
    6: "Other"
}

df_clean["Mode of Remittance"] = df['RQ25_MODE'].astype(str).str.strip().replace("", 7).astype(int).map(rq25_mode_mapping);
df_clean["Mode of Remittance"].value_counts()

Mode of Remittance
Money Transer Service    1623
Bank                     1184
Agency/Local Office        24
Other                      21
Friends/Co-workers          7
Door-to-Door                4
Name: count, dtype: int64

In [59]:
rq26_remittance_spent_mapping = {
    "A": "Consumptions",
    "B": "Investments",
    "C": "Savings",
    "D": "Gift/Donation",
    "E": "Other"
}

for code, label in rq26_remittance_spent_mapping.items():
    df_clean[label] = df["RQ26_REMITTANCE_SPENT"].fillna("").str.contains(code)

df_clean[["Consumptions", "Investments", "Savings", "Gift/Donation", "Other"]]

      Consumptions  Investments  Savings  Gift/Donation  Other
0             True        False    False          False  False
1            False        False    False          False  False
2            False        False    False          False  False
3             True        False    False          False  False
4             True        False    False          False  False
...            ...          ...      ...            ...    ...
4299          True        False    False          False  False
4300          True         True    False          False  False
4301          True        False    False          False  False
4302          True        False    False          False  False
4303          True        False    False          False  False

[4304 rows x 5 columns]

In [64]:
df_clean['Consumptions Percent'] = pandas.to_numeric(df["RQ261P_CONSUM"].str.strip(), errors="coerce")

df_clean["Consumptions Percent"]

0       100.0
1         NaN
2         NaN
3       100.0
4       100.0
        ...
4299    100.0
4300     50.0
4301    100.0
4302    100.0
4303    100.0
Name: Consumptions Percent, Length: 4304, dtype: float64

In [66]:
df_clean['Investments Percent'] = pandas.to_numeric(df["RQ262P_INVEST"].str.strip(), errors="coerce")

df_clean["Investments Percent"]

0        0.0
1        NaN
2        NaN
3        0.0
4        0.0
        ...
4299     0.0
4300    50.0
4301     0.0
4302     0.0
4303     0.0
Name: Investments Percent, Length: 4304, dtype: float64

In [67]:
df_clean['Savings Percent'] = pandas.to_numeric(df["RQ263P_SAVINGS"].str.strip(), errors="coerce")

df_clean["Savings Percent"]

0       0.0
1       NaN
2       NaN
3       0.0
4       0.0
       ...
4299    0.0
4300    0.0
4301    0.0
4302    0.0
4303    0.0
Name: Savings Percent, Length: 4304, dtype: float64

In [68]:
df_clean['Gift/Donation Percent'] = pandas.to_numeric(df["RQ264P_GIFT"].str.strip(), errors="coerce")

df_clean["Gift/Donation Percent"]

0       0.0
1       NaN
2       NaN
3       0.0
4       0.0
       ...
4299    0.0
4300    0.0
4301    0.0
4302    0.0
4303    0.0
Name: Gift/Donation Percent, Length: 4304, dtype: float64

In [69]:
df_clean['Other Percent'] = pandas.to_numeric(df["RQ265P_OTHERS"].str.strip(), errors="coerce")

df_clean["Other Percent"]

0       0.0
1       NaN
2       NaN
3       0.0
4       0.0
       ...
4299    0.0
4300    0.0
4301    0.0
4302    0.0
4303    0.0
Name: Other Percent, Length: 4304, dtype: float64

In [71]:
df_clean["Returned Apr-Sep"] = df["RQ27_RET6MOS"].map(rq14_indwork_mapping)
df_clean["Returned Apr-Sep"].value_counts()

0

Returned Apr-Sep
No     3513
Yes     791
Name: count, dtype: int64

In [75]:
df_clean["Cash Home"] = pd.to_numeric(df['RQ28_CASHHOME'].str.strip(), errors="coerce")
df_clean['Cash Home']

0           NaN
1           NaN
2           NaN
3       20000.0
4           NaN
         ...
4299        NaN
4300        NaN
4301        NaN
4302        NaN
4303        NaN
Name: Cash Home, Length: 4304, dtype: float64

In [78]:
df_clean["Receive Goods/Products"] = df["RQ29_INKIND"].map(rq14_indwork_mapping)

df_clean["Receive Goods/Products"]

0       Yes
1        No
2        No
3       Yes
4        No
       ...
4299     No
4300     No
4301     No
4302    Yes
4303     No
Name: Receive Goods/Products, Length: 4304, dtype: str

In [81]:
df_clean["Total Imputed Value of Goods/Products"] = pd.to_numeric(df["RQ30_KINDAMT"].str.strip(), errors="coerce")

df_clean["Total Imputed Value of Goods/Products"]

0       55000.0
1           NaN
2           NaN
3       30000.0
4           NaN
         ...
4299        NaN
4300        NaN
4301        NaN
4302    17000.0
4303        NaN
Name: Total Imputed Value of Goods/Products, Length: 4304, dtype: float64

In [86]:
df_clean["Past 6 Months Indicator"] = df["RP6M_IND"].str.strip().replace("",3).astype(int).map(rq14_indwork_mapping)

df_clean["Past 6 Months Indicator"]

0       NaN
1       NaN
2       NaN
3       Yes
4       Yes
       ...
4299    Yes
4300    Yes
4301    Yes
4302    Yes
4303    Yes
Name: Past 6 Months Indicator, Length: 4304, dtype: str

In [114]:
df_clean.to_csv("./dataset/SOF PUF 2023 - Clean.csv")

In [113]:
df.to_csv("./dataset/SOF PUF 2023.csv")